customhost = "database-1.c8hxcqxcu4hi.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "fongsukdien_employee"
custombucket = "fongsukdien-employee"
customregion = "us-east-1"
